--ignore-errors on add
just skip files which cannot be added because of errors

git add
The following paths are ignored by one of your .gitignore files:
Tests/Regression/Manager/Logs/macos-latest_3.8/Sikuli_java_stderr_1645540083.8068511.txt
Tests/Regression/Manager/Logs/macos-latest_3.8/Sikuli_java_stdout_1645540083.806635.txt
Error: Process completed with exit code 1.