Try to fix XMLSyntaxError error Issue #239
XMLSyntaxError: Opening and ending tag mismatch: img line 60 and div, line 60, column 20943 (file:/D:/a/rfswarm/rfswarm/Tests/Regression/Reporter/testdata/Issue-%23250/20240626_130059_jpetstore-nomon-quick/20240626_130059_jpetstore-nomon-quick.html, line 60)